# Generated by Django 2.1 on 2019-02-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('classification', models.CharField(choices=[('RAP', 'Rap'), ('ROCK', 'Rock'), ('POP', 'Pop')], default='POP', max_length=5)),
            ],
        ),
    ]
